version: '3.9'
services:
  serviceregistry:
    image: agarment/serviceregistry:0.0.1
    container_name: serviceregistry
    ports:
      - '8761:8761'
  configserver:
    image: agarment/configserver:0.0.1
    container_name: configserver
    ports:
      - '9296:9296'
    environment:
      - EUREKA_SERVER_ADDRESS=http://serviceregistry:8761/eureka
    healthcheck:
      test: ["CMD","curl", "http://configserver:9296/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - serviceregistry
  cloudgateway:
    image: agarment/cloudgateway:0.0.1
    container_name: cloudgateway
    ports:
      - '9090:9090'
    environment:
      - EUREKA_SERVER_ADDRESS=http://serviceregistry:8761/eureka
      - CONFIG_SERVER_ADDRESS=http://configserver:9296
    depends_on:
      configserver:
        condition: service_healthy
  orderservice:
    image: agarment/orderservice:0.0.1
    container_name: orderservice
    ports:
      - '8082:8082'
    environment:
      - EUREKA_SERVER_ADDRESS=http://serviceregistry:8761/eureka
      - CONFIG_SERVER_ADDRESS=http://configserver:9296
      - DB_HOST=host.docker.internal
    depends_on:
      configserver:
        condition: service_healthy
  productservice:
    image: agarment/productservice:0.0.1
    container_name: productservice
    ports:
      - '8080:8080'
    environment:
      - EUREKA_SERVER_ADDRESS=http://serviceregistry:8761/eureka
      - CONFIG_SERVER_ADDRESS=http://configserver:9296
      - DB_HOST=host.docker.internal
    depends_on:
      configserver:
        condition: service_healthy

  paymentservice:
    image: agarment/paymentservice:0.0.1
    container_name: paymentservice
    ports:
      - '8081:8081'
    environment:
      - EUREKA_SERVER_ADDRESS=http://serviceregistry:8761/eureka
      - CONFIG_SERVER_ADDRESS=http://configserver:9296
      - DB_HOST=host.docker.internal
    depends_on:
      configserver:
        condition: service_healthy